/* Auto-generated by build_dashboard_data.py — do not edit. */
const DASHBOARD_DATA = {
  "passages": [
    {
      "id": 7469,
      "name_en": "TPO60·L3·Balance Theory",
      "audio": "https://static.listeningo.cn/audio/whole/240429_17a60381c5355242c289dd8c.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p7469_c0_img83.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 0.672,
          "end": 160.811,
          "image": "/dual_pipeline_bundle/images/auto_p7469_c0_img22.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 46.099,
          "image_transition_at": 46.099
        },
        {
          "chunk_id": 1,
          "start": 162.273,
          "end": 283.014,
          "image": "/dual_pipeline_bundle/images/auto_p7469_c1_img23.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 168.093,
          "image_transition_at": 168.093
        },
        {
          "chunk_id": 2,
          "start": 284.096,
          "end": 393.323,
          "image": "/dual_pipeline_bundle/images/auto_p7469_c2_img24.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 287.939,
          "image_transition_at": 287.939
        }
      ]
    },
    {
      "id": 7484,
      "name_en": "TPO62·L2·Star formation",
      "audio": "https://static.listeningo.cn/audio/whole/240429_a10dd6da1bc2a1c32b7367c6.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p7484_c0_img84.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 0.503,
          "end": 100.572,
          "image": "/dual_pipeline_bundle/images/auto_p7484_c0_img25.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 43.932,
          "image_transition_at": 43.932
        },
        {
          "chunk_id": 1,
          "start": 101.264,
          "end": 197.176,
          "image": "/dual_pipeline_bundle/images/auto_p7484_c1_img26.png",
          "keyword_appearance_time": "mid",
          "keyword_estimated_at": 151.485,
          "image_transition_at": 151.485
        },
        {
          "chunk_id": 2,
          "start": 197.957,
          "end": 281.003,
          "image": "/dual_pipeline_bundle/images/auto_p7484_c2_img27.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 203.654,
          "image_transition_at": 203.654
        }
      ]
    },
    {
      "id": 7510,
      "name_en": "TPO66·L1·Sleep",
      "audio": "https://static.listeningo.cn/audio/whole/240429_6de6a0c369f725676e50001e.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p7510_c0_img74.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 0.031,
          "end": 109.669,
          "image": "/dual_pipeline_bundle/images/auto_p7510_c0_img19.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 3.095,
          "image_transition_at": 3.095
        },
        {
          "chunk_id": 1,
          "start": 110.591,
          "end": 237.706,
          "image": "/dual_pipeline_bundle/images/auto_p7510_c1_img20.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 113.136,
          "image_transition_at": 113.136
        },
        {
          "chunk_id": 2,
          "start": 238.326,
          "end": 323.646,
          "image": "/dual_pipeline_bundle/images/auto_p7510_c2_img21.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 243.799,
          "image_transition_at": 243.799
        }
      ]
    },
    {
      "id": 7520,
      "name_en": "TPO67·L2·Emotion and Memory",
      "audio": "https://static.listeningo.cn/audio/whole/240429_7df8e4b9d55d57f9d03a96c8.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p7520_c0_img65.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 1.297,
          "end": 88.58,
          "image": "/dual_pipeline_bundle/images/auto_p7520_c0_img1.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 20.376,
          "image_transition_at": 20.376
        },
        {
          "chunk_id": 1,
          "start": 89.161,
          "end": 221.474,
          "image": "/dual_pipeline_bundle/images/auto_p7520_c1_img2.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 110.079,
          "image_transition_at": 110.079
        },
        {
          "chunk_id": 2,
          "start": 222.936,
          "end": 311.007,
          "image": "/dual_pipeline_bundle/images/auto_p7520_c2_img3.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 225.733,
          "image_transition_at": 225.733
        }
      ]
    },
    {
      "id": 7573,
      "name_en": "TPO72·L3·Baby Memory",
      "audio": "https://static.listeningo.cn/audio/whole/240429_2cd43fa9e7cc6ebbaca69c8b.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p7573_c0_img66.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 0.031,
          "end": 105.679,
          "image": "/dual_pipeline_bundle/images/auto_p7573_c0_img1.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 5.92,
          "image_transition_at": 5.92
        },
        {
          "chunk_id": 1,
          "start": 107.441,
          "end": 196.499,
          "image": "/dual_pipeline_bundle/images/auto_p7573_c1_img2.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 115.99,
          "image_transition_at": 115.99
        },
        {
          "chunk_id": 2,
          "start": 198.162,
          "end": 318.938,
          "image": "/dual_pipeline_bundle/images/auto_p7573_c2_img333.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 203.86,
          "image_transition_at": 203.86
        }
      ]
    },
    {
      "id": 7795,
      "name_en": "TPO59·L1·The ever-changing ecosystem",
      "audio": "https://static.listeningo.cn/audio/whole/240429_57cf9c17830375db19316b56.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p7795_c0_img70.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 0.824,
          "end": 95.973,
          "image": "/dual_pipeline_bundle/images/auto_p7795_c0_img16.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 16.233,
          "image_transition_at": 16.233
        },
        {
          "chunk_id": 1,
          "start": 96.414,
          "end": 188.766,
          "image": "/dual_pipeline_bundle/images/auto_p7795_c1_img17.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 121.078,
          "image_transition_at": 121.078
        },
        {
          "chunk_id": 2,
          "start": 189.547,
          "end": 299.852,
          "image": "/dual_pipeline_bundle/images/auto_p7795_c2_img18.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 193.112,
          "image_transition_at": 193.112
        }
      ]
    },
    {
      "id": 9031,
      "name_en": "TPO43·L2·Approximate number sense",
      "audio": "https://static.listeningo.cn/audio/whole/240429_3e0abc1727b1d02b735865ef.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p9031_c0_img69.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 1.178,
          "end": 122.265,
          "image": "/dual_pipeline_bundle/images/auto_p9031_c0_img13.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 17.41,
          "image_transition_at": 17.41
        },
        {
          "chunk_id": 1,
          "start": 123.266,
          "end": 237.487,
          "image": "/dual_pipeline_bundle/images/auto_p9031_c1_img14.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 148.987,
          "image_transition_at": 148.987
        },
        {
          "chunk_id": 2,
          "start": 238.247,
          "end": 329.788,
          "image": "/dual_pipeline_bundle/images/auto_p9031_c2_img15.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 282.4,
          "image_transition_at": 282.4
        }
      ]
    },
    {
      "id": 9088,
      "name_en": "TPO36·L4·Gaussian Hypothesis",
      "audio": "https://static.listeningo.cn/audio/whole/240429_5a2cd75938a21989906599c5.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p9088_c0_img79.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 0.689,
          "end": 139.53,
          "image": "/dual_pipeline_bundle/images/auto_p9088_c0_img28.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 32.399,
          "image_transition_at": 32.399
        },
        {
          "chunk_id": 1,
          "start": 140.452,
          "end": 214.849,
          "image": "/dual_pipeline_bundle/images/auto_p9088_c1_img29.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 145.68,
          "image_transition_at": 145.68
        },
        {
          "chunk_id": 2,
          "start": 215.53,
          "end": 274.253,
          "image": "/dual_pipeline_bundle/images/auto_p9088_c2_img30.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 217.854,
          "image_transition_at": 217.854
        }
      ]
    },
    {
      "id": 9685,
      "name_en": "TPO35·L1·Animal Navigation System",
      "audio": "https://static.listeningo.cn/audio/whole/240429_dae0204607d6b74641eb0c6b.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p9685_c0_img67.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 0.773,
          "end": 87.48,
          "image": "/dual_pipeline_bundle/images/auto_p9685_c0_img7.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 75.013,
          "image_transition_at": 75.013
        },
        {
          "chunk_id": 1,
          "start": 87.46,
          "end": 193.804,
          "image": "/dual_pipeline_bundle/images/auto_p9685_c1_img8.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 87.46,
          "image_transition_at": 87.46
        },
        {
          "chunk_id": 2,
          "start": 194.625,
          "end": 252.838,
          "image": "/dual_pipeline_bundle/images/auto_p9685_c2_img9.png",
          "keyword_appearance_time": "late",
          "keyword_estimated_at": 249.333,
          "image_transition_at": 249.333
        }
      ]
    },
    {
      "id": 10510,
      "name_en": "TPO17·L2·Milankovitch hypothesis",
      "audio": "https://static.listeningo.cn/audio/whole/240429_8ea4634aa15b3779ef5b4cf0.mp3",
      "simpleImage": "/dual_pipeline_bundle/images/simple_p10510_c0_img68.png",
      "autoChunks": [
        {
          "chunk_id": 0,
          "start": 0.858,
          "end": 95.503,
          "image": "/dual_pipeline_bundle/images/auto_p10510_c0_img10.png",
          "keyword_appearance_time": "n/a",
          "keyword_estimated_at": 19.677,
          "image_transition_at": 19.677
        },
        {
          "chunk_id": 1,
          "start": 96.164,
          "end": 191.346,
          "image": "/dual_pipeline_bundle/images/auto_p10510_c1_img11.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 99.485,
          "image_transition_at": 99.485
        },
        {
          "chunk_id": 2,
          "start": 191.647,
          "end": 306.062,
          "image": "/dual_pipeline_bundle/images/auto_p10510_c2_img12.png",
          "keyword_appearance_time": "early",
          "keyword_estimated_at": 229.894,
          "image_transition_at": 229.894
        }
      ]
    }
  ]
};
